### ISSUE TITLE
Multiple SlideUnlock components of differing widths cause errant passVerify behavior due to duplicate element ids

### ISSUE THREAD

**Issue by Ephs05msm** [joseph2/vue-slide-unlock#21]
Hi - First, thank you for creating and maintaining this repository. It is very helpful!

A project I'm working on can display more than one SlideUnlock component on the page at a time. When this happens, the sliders are (purposefully) rendering at different widths due to the design of the page they appear on.

In this case, a slider may prematurely "unlock" (i.e., trigger the `passVerify` function) before the "handle" has been dragged fully across. As far as I can tell, this is because the width logic is grabbing the first element with the id "slideunlock", which may not be the same element that is being dragged in my case. I imagine that it can also fail the opposite way, where the slider won't unlock despite the handle being dragged all the way across, although I'm not experiencing this version of the issue. In any event, a link to at least one of the affected lines is below:

https://github.com/joseph2/vue-slide-unlock/blob/871a838d3fa31a94fcf99a977f5b1194998cbb5b/src/SlideUnlock.vue#L114

A solution to this likely involves ensuring that each instance of the slider has a unique id, which seems like a generally safe improvement.

Thanks in advance and happy to discuss further.

**Comment by joseph2** [comment]
@Ephs05msm Thank you very much for finding the problem! I fixed this in version 0.4.2. Now, when using multiple component instances on the same page, you need to set a unique identifier in the "name" prop for each instance. I also added a description of this prop in the README.

**Comment by Ephs05msm** [comment]
Thank you, @joseph2! Problem solved.👍
