### ISSUE TITLE
[Feature]: Complete trigger

### ISSUE THREAD

**Issue by vdiaza** [joseph2/vue-slide-unlock#24]
Nice work with this plugin.

I am looking somehow to trigger a function to mark the state as completed without sliding. Like in my case is for something that was already completed and I am saving the state on the DB.

Looking at the code I dont see a way of doing this, or am I wrong?

**Comment by joseph2** [comment]
Hello, @vdiaza. Thank you!
I made an additional "complete" method in the component to set the completed state.
More info about the method and how to use it in the README.
